# Generated by Django 2.1.7 on 2022-05-24 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220524_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 24, 12, 30, 24, 170092)),
        ),
    ]
